# -------------------------
# Backend Dockerfile
# -------------------------
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code
COPY . .

# Expose backend port
EXPOSE 5000

# Run the backend server
CMD ["npm", "run", "start"]
